# Generated by Django 2.2.3 on 2019-08-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogpost',
        ),
    ]
