# Generated by Django 2.2.3 on 2020-02-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
