# Generated by Django 2.2.3 on 2020-02-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200217_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
